- name: Install applications
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - slack-desktop
    - discord
    - gnucash
    - thunderbird
    - scrcpy

- name: Copy JetBrains Toolbox installation script
  ansible.builtin.copy:
    src: files/toolbox.sh
    dest: /tmp/toolbox.sh
    mode: '0755'

- name: Run JetBrains Toolbox installation script
  ansible.builtin.shell:
    cmd: /tmp/toolbox.sh
    creates: "$HOME/.local/bin/jetbrains-toolbox"