- name: Download Miniconda installer
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/Miniconda3-latest-Linux-x86_64.sh

- name: Run Miniconda installer
  shell: /bin/bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
  args:
    creates: $HOME/miniconda3  # Skip installation if Miniconda is already present

- name: Add Miniconda to PATH
  lineinfile:
    dest: "$HOME/.zshrc"
    line: 'export PATH="$HOME/miniconda3/bin:$PATH"'
  when: "'$HOME/miniconda3/bin' not in ansible_env.PATH"

- name: Environment file
  synchronize:
    # The trailing slash is very important here
    # It tells rsync to copy only the CONTENTS of the folder and not the folder itself
    # This is vital to make sure this works will any usernames
    src: files/
    dest: ~/miniconda3/
    recursive: true

- name: Create Conda environment
  command: "$HOME/miniconda3/bin/conda env create -n edurso -f ~/miniconda3/env.yml"
