- name: Install Docker
  become: True
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg

- name: Create directory for keyrings
  become: True
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  become: True
  shell: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'

- name: Set permissions for Docker GPG key
  become: True
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Add Docker repository to Apt sources
  become: True
  command: >
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Update Apt repositories
  become: True
  apt:
    update_cache: yes

- name: Upgrade APT Packages
  become: True
  apt:
    cache_valid_time: 604800
    state: latest
    upgrade: yes

- name: Install Docker packages
  become: True
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
