- name: Update package cache
  apt:
    update_cache: yes

- name: Install Ubuntu Desktop packages
  apt:
    name:
      - ubuntu-desktop
      - gnome
      - gnome-shell
      - gdm3  # GNOME Display Manager
    state: present

- name: Set GDM as the default display manager
  command: update-alternatives --config gdm3
  args:
    creates: /etc/X11/default-display-manager

- name: Add VSCode APT Key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/packages.microsoft.gpg

- name: Add VSCode APT List
  become: true
  apt_repository:
    filename: vscode
    repo: "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"

- name: Install APT Packages
  become: true
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - code
