- name: Install Linux headers
  apt:
    name: linux-headers-{{ ansible_kernel }}
    state: present

- name: Remove NVIDIA apt key
  apt_key:
    id: 7fa2af80
    state: absent

- name: Download CUDA keyring
  get_url:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    dest: /tmp/cuda-keyring_1.1-1_all.deb

- name: Install CUDA keyring
  command: dpkg -i /tmp/cuda-keyring_1.1-1_all.deb

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install CUDA Toolkit and NVIDIA GPU Drivers
  apt:
    name:
      - cuda
      - cuda-toolkit
      - nvidia-gds
    state: present

- name: Install NVIDIA Container Toolkit
  apt:
    name: nvidia-container-toolkit
    state: present
